name: Build and Publish images to Docker Hub
on: [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Add Docker Hub login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images
        run: docker build ./api/ -t movinliyanage/devops-qr-code-api:latest

      - name: Push Docker images
        run: docker push movinliyanage/devops-qr-code-api:latest
